In [5]:
import numpy as np
x = np.array([6, 4, 5, 7])
y = np.array([5, 1, 8, 7])
print(np.corrcoef(x, y))

[[1.         0.62554324]
 [0.62554324 1.        ]]

In [5]:
lista=[['East South Central','Alabama',2570.0,864.0,4887681],
     ['Pacific','Alaska',1434.0,582.0,735139],
     ['Mountain','Arizona',7259.0,2606.0,7158024],
     ['West South Central','Arkansas',2280.0,432.0,3009733],
     ['Pacific','California',109008.0,20964.0,39461588],
     ['Mountain','Colorado',7607.0,3250.0,5691287],
     ['New England','Connecticut',2280.0,1696.0,3571520],
     ['South Atlantic','Delaware',708.0,374.0,965479],
     ['South Atlantic','District of Columbia',3770.0,3134.0,701547],
     ['South Atlantic','Florida',21443.0,9587.0,21244317],
     ['South Atlantic','Georgia',6943.0,2556.0,10511131],
     ['Pacific','Hawaii',4131.0,2399.0,1420593],
     ['Mountain','Idaho',1297.0,715.0,1750536],
     ['East North Central','Illinois',6752.0,3891.0,12723071],
     ['East North Central','Indiana',3776.0,1482.0,6695497],
     ['West North Central','Iowa',1711.0,1038.0,3148618],
     ['West North Central','Kansas',1443.0,773.0,2911359],
     ['East South Central','Kentucky',2735.0,953.0,4461153],
     ['West South Central','Louisiana',2540.0,519.0,4659690],
     ['New England','Maine',1450.0,1066.0,1339057],
     ['South Atlantic','Maryland',4914.0,2230.0,6035802],
     ['New England','Massachusetts',6811.0,13257.0,6882635],
     ['East North Central','Michigan',5209.0,3142.0,9984072],
     ['West North Central','Minnesota',3993.0,3250.0,5606249],
     ['East South Central','Mississippi',1024.0,328.0,2981020],
     ['West North Central','Missouri',3776.0,2107.0,6121623],
     ['Mountain','Montana',983.0,422.0,1060665],
     ['West North Central','Nebraska',1745.0,676.0,1925614],
     ['Mountain','Nevada',7058.0,486.0,3027341],
     ['New England','New Hampshire',835.0,615.0,1353465],
     ['Mid-Atlantic','New Jersey',6048.0,3350.0,8886025],
     ['Mountain','New Mexico',1949.0,602.0,2092741],
     ['Mid-Atlantic','New York',39827.0,52070.0,19530351],
     ['South Atlantic','North Carolina',6451.0,2817.0,10381615],
     ['West North Central','North Dakota',467.0,75.0,758080],
     ['East North Central','Ohio',6929.0,3320.0,11676341],
     ['West South Central','Oklahoma',2823.0,1048.0,3940235],
     ['Pacific','Oregon',11139.0,3337.0,4181886],
     ['Mid-Atlantic','Pennsylvania',8163.0,5349.0,12800922],
     ['New England','Rhode Island',747.0,354.0,1058287],
     ['South Atlantic','South Carolina',3082.0,851.0,5084156],
     ['West North Central','South Dakota',836.0,323.0,878698],
     ['East South Central','Tennessee',6139.0,1744.0,6771631],
     ['West South Central','Texas',19199.0,6111.0,28628666],
     ['Mountain','Utah',1904.0,972.0,3153550],
     ['New England','Vermont',780.0,511.0,624358],
     ['South Atlantic','Virginia',3928.0,2047.0,8501286],
     ['Pacific','Washington',16424.0,5880.0,7523869],
     ['South Atlantic','West Virginia',1021.0,222.0,1804291],
     ['East North Central','Wisconsin',2740.0,2167.0,5807406],
     ['Mountain','Wyoming',434.0,205.0,577601]]

In [6]:
import pandas as pd
datacamp = pd.DataFrame(lista)
datacamp.row_column = ["P", "R", "S"]
print(datacamp)

                     0                     1         2        3         4
0   East South Central               Alabama    2570.0    864.0   4887681
1              Pacific                Alaska    1434.0    582.0    735139
2             Mountain               Arizona    7259.0   2606.0   7158024
3   West South Central              Arkansas    2280.0    432.0   3009733
4              Pacific            California  109008.0  20964.0  39461588
5             Mountain              Colorado    7607.0   3250.0   5691287
6          New England           Connecticut    2280.0   1696.0   3571520
7       South Atlantic              Delaware     708.0    374.0    965479
8       South Atlantic  District of Columbia    3770.0   3134.0    701547
9       South Atlantic               Florida   21443.0   9587.0  21244317
10      South Atlantic               Georgia    6943.0   2556.0  10511131
11             Pacific                Hawaii    4131.0   2399.0   1420593
12            Mountain                 Idaho    1297.0    715.0   1750536
13  East North Central              Illinois    6752.0   3891.0  12723071
14  East North Central               Indiana    3776.0   1482.0   6695497
15  West North Central                  Iowa    1711.0   1038.0   3148618
16  West North Central                Kansas    1443.0    773.0   2911359
17  East South Central              Kentucky    2735.0    953.0   4461153
18  West South Central             Louisiana    2540.0    519.0   4659690
19         New England                 Maine    1450.0   1066.0   1339057
20      South Atlantic              Maryland    4914.0   2230.0   6035802
21         New England         Massachusetts    6811.0  13257.0   6882635
22  East North Central              Michigan    5209.0   3142.0   9984072
23  West North Central             Minnesota    3993.0   3250.0   5606249
24  East South Central           Mississippi    1024.0    328.0   2981020
25  West North Central              Missouri    3776.0   2107.0   6121623
26            Mountain               Montana     983.0    422.0   1060665
27  West North Central              Nebraska    1745.0    676.0   1925614
28            Mountain                Nevada    7058.0    486.0   3027341
29         New England         New Hampshire     835.0    615.0   1353465
30        Mid-Atlantic            New Jersey    6048.0   3350.0   8886025
31            Mountain            New Mexico    1949.0    602.0   2092741
32        Mid-Atlantic              New York   39827.0  52070.0  19530351
33      South Atlantic        North Carolina    6451.0   2817.0  10381615
34  West North Central          North Dakota     467.0     75.0    758080
35  East North Central                  Ohio    6929.0   3320.0  11676341
36  West South Central              Oklahoma    2823.0   1048.0   3940235
37             Pacific                Oregon   11139.0   3337.0   4181886
38        Mid-Atlantic          Pennsylvania    8163.0   5349.0  12800922
39         New England          Rhode Island     747.0    354.0   1058287
40      South Atlantic        South Carolina    3082.0    851.0   5084156
41  West North Central          South Dakota     836.0    323.0    878698
42  East South Central             Tennessee    6139.0   1744.0   6771631
43  West South Central                 Texas   19199.0   6111.0  28628666
44            Mountain                  Utah    1904.0    972.0   3153550
45         New England               Vermont     780.0    511.0    624358
46      South Atlantic              Virginia    3928.0   2047.0   8501286
47             Pacific            Washington   16424.0   5880.0   7523869
48      South Atlantic         West Virginia    1021.0    222.0   1804291
49  East North Central             Wisconsin    2740.0   2167.0   5807406
50            Mountain               Wyoming     434.0    205.0    577601

C:\Users\sicha\AppData\Local\Temp\ipykernel_7816\2638182003.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  datacamp.row_column = ["P", "R", "S"]

In [1]:
False==1

False

In [20]:
dict={'X':[2,8,7,4,5,6,7],'Y':[15,10,7,4,5,6,7]}
print(dict)

{'X': [2, 8, 7, 4, 5, 6, 7], 'Y': [15, 10, 7, 4, 5, 6, 7]}

In [22]:
import pandas as pd
df=pd.DataFrame(dict)
print(df.head())

   X   Y
0  2  15
1  8  10
2  7   7
3  4   4
4  5   5

In [19]:
df.index=['a','b']
#print(df)
#print(df.iloc[1])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, a to b
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       2 non-null      int64
 1   Y       2 non-null      int64
dtypes: int64(2)
memory usage: 48.0+ bytes

In [11]:
for j, p in df.iterrows():
    print(j)
    print(p)

a
X     2
Y    15
Name: a, dtype: int64
b
X     8
Y    10
Name: b, dtype: int64

In [12]:
z = "regulation"
print(z.replace("a", "/"))

regul/tion

In [14]:
from math import cos

In [15]:
cos(90)

-0.4480736161291701

In [16]:
x = "python" + " exercise"
x.capitalize()

'Python exercise'

In [2]:
datacamp = { 'course':'python', 'level':'intermediate', 'lesson': {'dictionaries':'python', 'lists':'r' } }

In [3]:
datacamp

{'course': 'python',
 'level': 'intermediate',
 'lesson': {'dictionaries': 'python', 'lists': 'r'}}

In [9]:
datacamp.keys()

dict_keys(['course', 'level', 'lesson'])

In [10]:
datacamp = { 'course':'python', 'level':'intermediate', 'lesson': {'dictionaries':'python', 'lists':'r' } }

In [11]:
datacamp

{'course': 'python',
 'level': 'intermediate',
 'lesson': {'dictionaries': 'python', 'lists': 'r'}}

In [12]:
del(datacamp["lesson"]["lists"])

In [13]:
datacamp

{'course': 'python',
 'level': 'intermediate',
 'lesson': {'dictionaries': 'python'}}

In [14]:
datacamp["lesson"]['project'] = 'sql'
print(datacamp)

{'course': 'python', 'level': 'intermediate', 'lesson': {'dictionaries': 'python', 'project': 'sql'}}

In [27]:
import pandas as pd
churn=pd.read_csv('data.csv',sep=';')
print(churn.head())

    surname  credit_score geography  age exited
0  Hargrave           619    France   42    Yes
1      Hill           608     Spain   41     No
2      Onio           502    France   42    Yes
3      Boni           699    France   39     No
4  Mitchell           850     Spain   43     No

In [31]:
print(churn[(churn["exited"] =="Yes")&(churn["credit_score"]< 600)])

    surname  credit_score geography  age exited
0  Hargrave           619    France   42    Yes
2      Onio           502    France   42    Yes

In [32]:
a=churn[['surname','geography']]
print(a)

    surname geography
0  Hargrave    France
1      Hill     Spain
2      Onio    France
3      Boni    France
4  Mitchell     Spain

In [37]:
a[a['geography'].isin(['France'])]

    surname geography
0  Hargrave    France
2      Onio    France
3      Boni    France

In [2]:
import pandas as pd
sales=pd.read_csv('data.csv',sep=';')
print(sales.head())

        date            product_line     product  unit_price  quantity
0  15/1/2018       Health and beauty     Shampoo        6.99         7
1  15/1/2018  Electronic accessories    Keyboard       49.99         5
2  16/1/2018      Home and lifestyle        Lamp       46.33         3
3  16/1/2018                  Sports    Yoga mat       39.99         5
4  17/1/2018  Electronic accessories  Headphones       12.99         8

In [42]:
print(sales[(sales["product_line"] != "Electronic accessories")|(sales["unit_price"]> 20)])

        date            product_line   product  unit_price  quantity
0  15/1/2018       Health and beauty   Shampoo        6.99         7
1  15/1/2018  Electronic accessories  Keyboard       49.99         5
2  16/1/2018      Home and lifestyle      Lamp       46.33         3
3  16/1/2018                  Sports  Yoga mat       39.99         5

In [3]:
import numpy as np
np_array1 = np.array([1, 2, 3])
np_array2 = np.array([4, 5, 6])
np_array = np.array([np_array1, np_array2])

for val in np_array:
  print(val)

[1 2 3]
[4 5 6]

In [ ]:
!pip install matplotlib

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [3]:
import funpymodeling as fp

ModuleNotFoundError: No module named 'sklearn'

In [4]:
from funpymodeling.exploratory import status

In [7]:
datacamp

                     0                     1         2        3         4
0   East South Central               Alabama    2570.0    864.0   4887681
1              Pacific                Alaska    1434.0    582.0    735139
2             Mountain               Arizona    7259.0   2606.0   7158024
3   West South Central              Arkansas    2280.0    432.0   3009733
4              Pacific            California  109008.0  20964.0  39461588
5             Mountain              Colorado    7607.0   3250.0   5691287
6          New England           Connecticut    2280.0   1696.0   3571520
7       South Atlantic              Delaware     708.0    374.0    965479
8       South Atlantic  District of Columbia    3770.0   3134.0    701547
9       South Atlantic               Florida   21443.0   9587.0  21244317
10      South Atlantic               Georgia    6943.0   2556.0  10511131
11             Pacific                Hawaii    4131.0   2399.0   1420593
12            Mountain                 Idaho    1297.0    715.0   1750536
13  East North Central              Illinois    6752.0   3891.0  12723071
14  East North Central               Indiana    3776.0   1482.0   6695497
15  West North Central                  Iowa    1711.0   1038.0   3148618
16  West North Central                Kansas    1443.0    773.0   2911359
17  East South Central              Kentucky    2735.0    953.0   4461153
18  West South Central             Louisiana    2540.0    519.0   4659690
19         New England                 Maine    1450.0   1066.0   1339057
20      South Atlantic              Maryland    4914.0   2230.0   6035802
21         New England         Massachusetts    6811.0  13257.0   6882635
22  East North Central              Michigan    5209.0   3142.0   9984072
23  West North Central             Minnesota    3993.0   3250.0   5606249
24  East South Central           Mississippi    1024.0    328.0   2981020
25  West North Central              Missouri    3776.0   2107.0   6121623
26            Mountain               Montana     983.0    422.0   1060665
27  West North Central              Nebraska    1745.0    676.0   1925614
28            Mountain                Nevada    7058.0    486.0   3027341
29         New England         New Hampshire     835.0    615.0   1353465
30        Mid-Atlantic            New Jersey    6048.0   3350.0   8886025
31            Mountain            New Mexico    1949.0    602.0   2092741
32        Mid-Atlantic              New York   39827.0  52070.0  19530351
33      South Atlantic        North Carolina    6451.0   2817.0  10381615
34  West North Central          North Dakota     467.0     75.0    758080
35  East North Central                  Ohio    6929.0   3320.0  11676341
36  West South Central              Oklahoma    2823.0   1048.0   3940235
37             Pacific                Oregon   11139.0   3337.0   4181886
38        Mid-Atlantic          Pennsylvania    8163.0   5349.0  12800922
39         New England          Rhode Island     747.0    354.0   1058287
40      South Atlantic        South Carolina    3082.0    851.0   5084156
41  West North Central          South Dakota     836.0    323.0    878698
42  East South Central             Tennessee    6139.0   1744.0   6771631
43  West South Central                 Texas   19199.0   6111.0  28628666
44            Mountain                  Utah    1904.0    972.0   3153550
45         New England               Vermont     780.0    511.0    624358
46      South Atlantic              Virginia    3928.0   2047.0   8501286
47             Pacific            Washington   16424.0   5880.0   7523869
48      South Atlantic         West Virginia    1021.0    222.0   1804291
49  East North Central             Wisconsin    2740.0   2167.0   5807406
50            Mountain               Wyoming     434.0    205.0    577601

In [8]:
status(datacamp)

   variable  q_nan  p_nan  q_zeros  p_zeros  unique     type
0         0      0    0.0        0      0.0       9   object
1         1      0    0.0        0      0.0      51   object
2         2      0    0.0        0      0.0      49  float64
3         3      0    0.0        0      0.0      50  float64
4         4      0    0.0        0      0.0      51    int64

In [1]:
import pandas as pd
avocados=pd.read_csv('avocado.csv')

In [3]:
avocados.isna()

       date   type   year  avg_price   size  nb_sold
0     False  False  False      False  False    False
1     False  False  False      False  False    False
2     False  False  False      False  False    False
3     False  False  False      False  False    False
4     False  False  False      False  False    False
...     ...    ...    ...        ...    ...      ...
1009  False  False  False      False  False    False
1010  False  False  False      False  False    False
1011  False  False  False      False  False    False
1012  False  False  False      False  False    False
1013  False  False  False      False  False    False

[1014 rows x 6 columns]

In [5]:
avocados.isna().sum()

date         0
type         0
year         0
avg_price    0
size         0
nb_sold      0
dtype: int64

In [6]:
avocados.isna().any()

date         False
type         False
year         False
avg_price    False
size         False
nb_sold      False
dtype: bool